name: Publish image to Docker Hub
on: 
  push: 
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build . -t kaleosanchez/final_project:latest
      - name: publish
        run: |
          docker login -u kaleosanchez -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push kaleosanchez/final_project:latest
      - name: pull
        run: |
          docker login -u kaleosanchez -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker pull kaleosanchez/final_project:latest 
